from typing import Callable, Protocol


class DevicePort(Protocol):
    def is_connected(self) -> bool: ...
    def shell(self, *args: str) -> str: ...
    def start_app(self, package: str) -> None: ...
    def stop_app(self, package: str) -> None: ...
    def screenshot(self) -> bytes: ...
    def current_activity(self) -> str: ...
    def list_packages(self) -> set[str]: ...


class AutomationPort(Protocol):
    def recover(self) -> None: ...
    def open(self) -> None: ...
    def is_ready(self) -> bool: ...
    def open_chat(self, phone_number: str) -> None: ...
    def send(self, message, media, before_send: Callable[[], None]) -> None: ...
    def get_current_screen(self) -> str: ...
    def evidence(self, message_id) -> dict: ...
    def close(self) -> None: ...
